- name: Update package
  apt:
    update_cache: yes
  when: "ansible_os_family == 'Debian'"

- name: Install dependency
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: "ansible_os_family == 'Debian'"
  