- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable
  when: "ansible_os_family == 'Debian'"

- name: Update package 
  apt:
    update_cache: yes
  when: "ansible_os_family == 'Debian'"

- name: Install Docker on hosts
  package:
    name: docker-ce
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
  when: "ansible_os_family == 'Debian'"

- name: Add user to docker group
  user:
    name: ferrati_igor
    groups: docker
    append: yes
  when: "ansible_os_family == 'Debian'"
  